<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'SessionHandlerInterface' => '/Component/HttpFoundation/Resources/stubs/SessionHandlerInterface.php',
                'Symfony\\Component\\HttpFoundation\\AcceptHeader' => '/Component/HttpFoundation/AcceptHeader.php',
                'Symfony\\Component\\HttpFoundation\\AcceptHeaderItem' => '/Component/HttpFoundation/AcceptHeaderItem.php',
                'Symfony\\Component\\HttpFoundation\\ApacheRequest' => '/Component/HttpFoundation/ApacheRequest.php',
                'Symfony\\Component\\HttpFoundation\\BinaryFileResponse' => '/Component/HttpFoundation/BinaryFileResponse.php',
                'Symfony\\Component\\HttpFoundation\\Cookie' => '/Component/HttpFoundation/Cookie.php',
                'Symfony\\Component\\HttpFoundation\\ExpressionRequestMatcher' => '/Component/HttpFoundation/ExpressionRequestMatcher.php',
                'Symfony\\Component\\HttpFoundation\\FileBag' => '/Component/HttpFoundation/FileBag.php',
                'Symfony\\Component\\HttpFoundation\\File\\Exception\\AccessDeniedException' => '/Component/HttpFoundation/File/Exception/AccessDeniedException.php',
                'Symfony\\Component\\HttpFoundation\\File\\Exception\\FileException' => '/Component/HttpFoundation/File/Exception/FileException.php',
                'Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException' => '/Component/HttpFoundation/File/Exception/FileNotFoundException.php',
                'Symfony\\Component\\HttpFoundation\\File\\Exception\\UnexpectedTypeException' => '/Component/HttpFoundation/File/Exception/UnexpectedTypeException.php',
                'Symfony\\Component\\HttpFoundation\\File\\Exception\\UploadException' => '/Component/HttpFoundation/File/Exception/UploadException.php',
                'Symfony\\Component\\HttpFoundation\\File\\File' => '/Component/HttpFoundation/File/File.php',
                'Symfony\\Component\\HttpFoundation\\File\\MimeType\\ExtensionGuesser' => '/Component/HttpFoundation/File/MimeType/ExtensionGuesser.php',
                'Symfony\\Component\\HttpFoundation\\File\\MimeType\\ExtensionGuesserInterface' => '/Component/HttpFoundation/File/MimeType/ExtensionGuesserInterface.php',
                'Symfony\\Component\\HttpFoundation\\File\\MimeType\\FileBinaryMimeTypeGuesser' => '/Component/HttpFoundation/File/MimeType/FileBinaryMimeTypeGuesser.php',
                'Symfony\\Component\\HttpFoundation\\File\\MimeType\\FileinfoMimeTypeGuesser' => '/Component/HttpFoundation/File/MimeType/FileinfoMimeTypeGuesser.php',
                'Symfony\\Component\\HttpFoundation\\File\\MimeType\\MimeTypeExtensionGuesser' => '/Component/HttpFoundation/File/MimeType/MimeTypeExtensionGuesser.php',
                'Symfony\\Component\\HttpFoundation\\File\\MimeType\\MimeTypeGuesser' => '/Component/HttpFoundation/File/MimeType/MimeTypeGuesser.php',
                'Symfony\\Component\\HttpFoundation\\File\\MimeType\\MimeTypeGuesserInterface' => '/Component/HttpFoundation/File/MimeType/MimeTypeGuesserInterface.php',
                'Symfony\\Component\\HttpFoundation\\File\\UploadedFile' => '/Component/HttpFoundation/File/UploadedFile.php',
                'Symfony\\Component\\HttpFoundation\\HeaderBag' => '/Component/HttpFoundation/HeaderBag.php',
                'Symfony\\Component\\HttpFoundation\\IpUtils' => '/Component/HttpFoundation/IpUtils.php',
                'Symfony\\Component\\HttpFoundation\\JsonResponse' => '/Component/HttpFoundation/JsonResponse.php',
                'Symfony\\Component\\HttpFoundation\\ParameterBag' => '/Component/HttpFoundation/ParameterBag.php',
                'Symfony\\Component\\HttpFoundation\\RedirectResponse' => '/Component/HttpFoundation/RedirectResponse.php',
                'Symfony\\Component\\HttpFoundation\\Request' => '/Component/HttpFoundation/Request.php',
                'Symfony\\Component\\HttpFoundation\\RequestMatcher' => '/Component/HttpFoundation/RequestMatcher.php',
                'Symfony\\Component\\HttpFoundation\\RequestMatcherInterface' => '/Component/HttpFoundation/RequestMatcherInterface.php',
                'Symfony\\Component\\HttpFoundation\\RequestStack' => '/Component/HttpFoundation/RequestStack.php',
                'Symfony\\Component\\HttpFoundation\\Response' => '/Component/HttpFoundation/Response.php',
                'Symfony\\Component\\HttpFoundation\\ResponseHeaderBag' => '/Component/HttpFoundation/ResponseHeaderBag.php',
                'Symfony\\Component\\HttpFoundation\\ServerBag' => '/Component/HttpFoundation/ServerBag.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Attribute\\AttributeBag' => '/Component/HttpFoundation/Session/Attribute/AttributeBag.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Attribute\\AttributeBagInterface' => '/Component/HttpFoundation/Session/Attribute/AttributeBagInterface.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Attribute\\NamespacedAttributeBag' => '/Component/HttpFoundation/Session/Attribute/NamespacedAttributeBag.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Flash\\AutoExpireFlashBag' => '/Component/HttpFoundation/Session/Flash/AutoExpireFlashBag.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Flash\\FlashBag' => '/Component/HttpFoundation/Session/Flash/FlashBag.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Flash\\FlashBagInterface' => '/Component/HttpFoundation/Session/Flash/FlashBagInterface.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Session' => '/Component/HttpFoundation/Session/Session.php',
                'Symfony\\Component\\HttpFoundation\\Session\\SessionBagInterface' => '/Component/HttpFoundation/Session/SessionBagInterface.php',
                'Symfony\\Component\\HttpFoundation\\Session\\SessionInterface' => '/Component/HttpFoundation/Session/SessionInterface.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\MemcacheSessionHandler' => '/Component/HttpFoundation/Session/Storage/Handler/MemcacheSessionHandler.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\MemcachedSessionHandler' => '/Component/HttpFoundation/Session/Storage/Handler/MemcachedSessionHandler.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\MongoDbSessionHandler' => '/Component/HttpFoundation/Session/Storage/Handler/MongoDbSessionHandler.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\NativeFileSessionHandler' => '/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\NativeSessionHandler' => '/Component/HttpFoundation/Session/Storage/Handler/NativeSessionHandler.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\NullSessionHandler' => '/Component/HttpFoundation/Session/Storage/Handler/NullSessionHandler.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\PdoSessionHandler' => '/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\WriteCheckSessionHandler' => '/Component/HttpFoundation/Session/Storage/Handler/WriteCheckSessionHandler.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\MetadataBag' => '/Component/HttpFoundation/Session/Storage/MetadataBag.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\MockArraySessionStorage' => '/Component/HttpFoundation/Session/Storage/MockArraySessionStorage.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\MockFileSessionStorage' => '/Component/HttpFoundation/Session/Storage/MockFileSessionStorage.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage' => '/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\PhpBridgeSessionStorage' => '/Component/HttpFoundation/Session/Storage/PhpBridgeSessionStorage.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Proxy\\AbstractProxy' => '/Component/HttpFoundation/Session/Storage/Proxy/AbstractProxy.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Proxy\\NativeProxy' => '/Component/HttpFoundation/Session/Storage/Proxy/NativeProxy.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\Proxy\\SessionHandlerProxy' => '/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php',
                'Symfony\\Component\\HttpFoundation\\Session\\Storage\\SessionStorageInterface' => '/Component/HttpFoundation/Session/Storage/SessionStorageInterface.php',
                'Symfony\\Component\\HttpFoundation\\StreamedResponse' => '/Component/HttpFoundation/StreamedResponse.php'
            );
        }
        if (isset($classes[$class])) {
            require __DIR__ . "/vendors/Symfony" . $classes[$class];
        }
     }
);
// @codeCoverageIgnoreEnd


